name: Reviewer

on:
  pull_request
jobs:
  prLabeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Head
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: composer install
      run: |
        composer install
